"""empty message

Revision ID: 0438f63d4e33
Revises: 7a7109894532
Create Date: 2022-05-29 16:43:49.739583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0438f63d4e33'
down_revision = '7a7109894532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos','completed', nullable =False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
